/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lime;

import org.junit.Test;
import static org.junit.Assert.*;

public class LimeApplicationTest {
  //    @Test public void appHasAGreeting() {
  //        LimeApplication classUnderTest = new LimeApplication();
  //        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
}
}
