/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lime;

public class LimeApplication {
    public String getGreeting() {
      System.out.println("omh1004 test");
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new LimeApplication().getGreeting());
    }
}
